<h1>My notebook</h1>
<p>
    This is my first notebook.
</p>

In [2]:
2 + 3

5

In [3]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
from math import sqrt

In [6]:
sqrt(81)

9.0

In [7]:
u = np.array([2, -7, 1])

In [8]:
u

array([ 2, -7,  1])

In [9]:
v = np.array([-3, 0, 4])

In [10]:
v

array([-3,  0,  4])

In [11]:
u + v

array([-1, -7,  5])

In [12]:
-3 * u

array([-6, 21, -3])

In [13]:
u.dot(v)

-2

In [14]:
u.dot(u)

54

In [15]:
np.sqrt(u.dot(u))

7.3484692283495345

In [16]:
u.dot(v)

-2

In [17]:
u * v

array([-6,  0,  4])

In [18]:
A = np.array([[1, 2, 0],
            [3, -1, 4]])

In [19]:
A

array([[ 1,  2,  0],
       [ 3, -1,  4]])

In [20]:
B = np.array([[2, -1],
             [1, 0],
             [-3, 4]])

In [21]:
B

array([[ 2, -1],
       [ 1,  0],
       [-3,  4]])

In [22]:
A + A

array([[ 2,  4,  0],
       [ 6, -2,  8]])

In [23]:
A + u

array([[ 3, -5,  1],
       [ 5, -8,  5]])

In [24]:
10 * A

array([[ 10,  20,   0],
       [ 30, -10,  40]])

In [25]:
A.dot(v)

array([-3,  7])

In [26]:
A.dot(B)

array([[ 4, -1],
       [-7, 13]])

In [27]:
A.T

array([[ 1,  3],
       [ 2, -1],
       [ 0,  4]])

In [28]:
A.dot(A.T)

array([[ 5,  1],
       [ 1, 26]])

In [29]:
A.T.dot(A)

array([[10, -1, 12],
       [-1,  5, -4],
       [12, -4, 16]])

In [30]:
u.min()

-7

In [31]:
u.argmin()

1

In [32]:
u.mean()

-1.3333333333333333

In [61]:
help(np.cumsum)

Help on function cumsum in module numpy.core.fromnumeric:

cumsum(a, axis=None, dtype=None, out=None)
    Return the cumulative sum of the elements along a given axis.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis : int, optional
        Axis along which the cumulative sum is computed. The default
        (None) is to compute the cumsum over the flattened array.
    dtype : dtype, optional
        Type of the returned array and of the accumulator in which the
        elements are summed.  If `dtype` is not specified, it defaults
        to the dtype of `a`, unless `a` has an integer dtype with a
        precision less than that of the default platform integer.  In
        that case, the default platform integer is used.
    out : ndarray, optional
        Alternative output array in which to place the result. It must
        have the same shape and buffer length as the expected output
        but the type will be cast if necessary. See `doc.ufuncs`

In [63]:
def my_cumsum(lis):
    res = []
    current_sum = 0
    for element in lis:
        current_sum += element
        res.append(current_sum)
    return res

play with the cumsum method on 1-dimensional numpy arrays. Then define a python function that does the same thing for regular Python lists. Then compare how long they take to run on an arraylist that contains all the integers from 1 to 1000 inclusive.

In [64]:
%timeit np.cumsum(np.arange(1, 1001))

4.41 µs ± 9.92 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [65]:
%timeit my_cumsum(range(1, 1001))

77.6 µs ± 36.8 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [67]:
my_cumsum([1, 2, 3, 4, 5])

[1, 3, 6, 10, 15]